# Generated by Django 4.2.9 on 2024-02-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GYMapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emmodel",
            name="department",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="emmodel",
            name="position",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
